spring:
  application:
    name: fulfillment-center-task
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml